### ISSUE TITLE
Should use Path variables or config file in ddl.

### ISSUE THREAD

**Issue by calimpio** [malware-dev/MDK-Debug#4]
I think that this resolve the problem with SE folder or what ever info user need.

**Comment by malware-dev** [comment]
I don't understand what you mean.  What problem with SE folder?

**Comment by calimpio** [comment]
this resolve that: https://github.com/malware-dev/MDK-Debug/issues/1#issuecomment-671748396
if you compile a ddl realise for final user.

**Comment by malware-dev** [comment]
Ah. No, that's a compile-time problem only. The _compiler_ needs to know where to find the assemblies. This is not a problem for the compiled plugin itself, because the game assemblies will already be loaded - or they're already referenced and has a load path.

**Comment by calimpio** [comment]
OK good.
