### ISSUE TITLE
Assertion Failed

### ISSUE THREAD

**Issue by ghost** [malware-dev/MDK-Debug#5]
When I follow the guide, I get the following error on startup.
![grafik](https://user-images.githubusercontent.com/44356373/123030543-4397f080-d3e3-11eb-88a1-4f284ef0f8e4.png)

**Comment by AnubisX9** [comment]
Same

**Comment by malware-dev** [comment]
Probably needs another reimaging.

Also how the hell did I miss OP's post? :anger:

**Comment by malware-dev** [comment]
Fixed.
